ChatApp/urls.py
from django.contrib import admin
from django.urls import path, include
from chat.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
    path('', home, name='home')
]

chat/urls.py
from django.urls import path
from chat.views import chat_page, signup_view
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'chat'

urlpatterns = [
    path('with/user/', chat_page, name='chat_page'),
    path('login/', LoginView.as_view(template_name='chat/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', signup_view, name='signup'),
]

chat/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.
class Message(models.Model):
    sender = models.ForeignKey(get_user_model(), verbose_name='sender', on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(get_user_model(), verbose_name='receiver', on_delete=models.CASCADE, related_name='receiver')
    content = models.TextField()
    chat_id = models.CharField(max_length=127)
    timestamp = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.sender} -> {self.receiver}"
    

chat/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class SignupForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'first_name', 'last_name']

chat/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from django.contrib.auth import login
from .forms import SignupForm
from chat.models import Message
from django.db.models import Q
from django.contrib.auth.decorators import login_required

from django.urls import reverse

# Create your views here.
@login_required
def chat_page(request, *args, **kwargs):
    user_object = get_user_model().objects.get(username=request.user.username)
    users = get_user_model().objects.exclude(username=request.user.username)
    messages = Message.objects.filter(
        Q(sender=user_object) | Q(receiver=user_object)
    ).order_by('timestamp')
    group = {}
    for message in messages:
        if message.chat_id not in group:
            group[message.chat_id] = []
        group[message.chat_id].append(message)
    context = {
        'users_list': users,
        'user_object': user_object,
        'groups': group,
    }
    return render(request, 'chat/chat.html', context)

def signup_view(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(reverse('chat:chat_page'))
        return render(request, 'chat/signup.html', {'errors': form.errors, 'form': form})
    else:
        form = SignupForm()
    
    return render(request, 'chat/signup.html', {'form': form})

def home(request):
    return render(request, 'chat/home.html')

chat/templates/chat/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chat App</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>

<body style="font-family: 'Times New Roman', Times, serif;">
    <nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand mx-5 fs-3" href="">Chat App</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item mx-5">
                        <a class="nav-link active fs-4" href="">Welcome {{ user.username }}</a>
                    </li>
                </ul>
                <form class="d-flex me-5" role="search" action="{% url 'chat:logout' %}" method="post">
                    {% csrf_token %}
                    {% if user.is_authenticated %}
                    <button class="btn btn-outline-danger ms-5 px-3 fs-5" type="submit">Logout</button>
                    {% else %}
                    <a href="{% url 'chat:login' %}" class="btn btn-outline-success me-4 px-3 fs-5">Login</a>
                    <a href="{% url 'chat:signup' %}" class="btn btn-outline-warning px-3 fs-5">Signup</a>
                    {% endif %}
                </form>
            </div>
        </div>
    </nav>
    <div id="body">
        {% block body %}{% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
        integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
        crossorigin="anonymous"></script>

    <script src="{% static 'scripts.js' %}"></script>
</body>

</html>

chat/templates/chat/chat.html
{% extends 'chat/base.html' %}
{% load static %}

{% block title %}Chat{% endblock %}
{% block body %}
<p>After starting a new conversation please refresh to experience the design</p>
  <div class="container my-3">

    <div class="card">
      <div class="card-body">

        <div class="row">

          <div class="col-md-4">
            <h2>Chat with ...</h2>
            <div class="users">
              {% for other_user in users_list %}
              <div class="card my-3" onclick="openChat('{{other_user.id}}', '{{user.id}}')">
                <div class="card-body">
                  <h5 class="card-title">{{ other_user.username }}</h5>
                </div>
              </div>
              {% endfor %}
            </div>
          </div>


          <div class="col-md-8" id="chatPanel">
            {% for group, messages in groups.items %}
            <div id="chat-{{group}}" class="chat">
              {% for message in messages %}
              {% if forloop.counter0 == 0 %}
              <div class="userinfo">
                {% if message.sender != user %}
                <h3>Chating with {{message.sender}}</h3>
                {% else %}
                <h3>Chating With {{message.receiver}}</h3>
                {% endif %}
              </div>
              {% endif %}
              {% if message.sender == user %}
              <p class="toUser">{{message.content}}</p>
              <span class="toUserTime">{{message.timestamp | time:'g:i A'}}</span>
              {% else %}
              <p class="fromUser">{{message.content}}</p>
              <span class="fromUserTime">{{message.timestamp | time:'g:i A'}}</span>
              {% endif %}
              {% endfor %}
              <div id="chat_container_{{group}}"></div>
              <input type="text" id="messageInput_{{group}}" placeholder="Type your message here">
              <button id="sendMessage" type="button" class="btn btn-success fs-4"><i
                  class="bi bi-send-fill"></i></button>
            </div>
            {% endfor %}

            <div class="newChat">
              <div></div>
              <input type="text" placeholder="Type your message here">
              <button id="sendMessage" type="button" class="btn btn-success fs-4"><i
                  class="bi bi-send-fill"></i></button>
            </div>
          </div>
        </div>

      </div>

    </div>
{% endblock %}

chat/templates/chat/home.html
{% extends 'chat/base.html' %}
{% block body %}
<a href="{% url 'chat:chat_page' %}" class="btn btn-outline-success form-control my-5">Go to chat</a>
{% endblock %}

chat/templates/chat/login.html
{% extends 'chat/base.html' %}
{% block title %}Login{% endblock %}
{% block body %}
<div class="row container-fluid">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <h1 class="text-center">Login</h1>
        <form action="" method="post">
            {% csrf_token %}
            <label for="username">Username:</label><br>
            <input type="text" id="username" name="username" class="form-control"><br>
            <label for="password">Password:</label><br>
            <input type="password" id="password" name="password" class="form-control"><br>
            <input type="submit" value="Login" class="btn btn-outline-success form-control">
        </form>
    </div>
</div>
{% endblock %}

chat/templates/chat/signup.html
{% extends 'chat/base.html' %}
{% block title %}SignUp{% endblock %}

{% block body %}
{% if errors %}
<div class="container">
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{errors}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
</div>
{% endif %}
<div class="row container-fluid my-3">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <h2 class="text-center">Signup</h2>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-outline-warning mb-3 form-control">Signup</button>
        </form>
    </div>
</div>
<script>
    var username = document.getElementById('id_username');
    var email = document.getElementById('id_email');
    var password1 = document.getElementById('id_password1');
    var password2 = document.getElementById('id_password2');
    var first_name = document.getElementById('id_first_name');
    var last_name = document.getElementById('id_last_name');
    username.classList.add('form-control');
    email.classList.add('form-control');
    password1.classList.add('form-control');
    password2.classList.add('form-control');
    first_name.classList.add('form-control');
    last_name.classList.add('form-control');
    username.placeholder = 'Username';
    email.placeholder = 'Email';
    password1.placeholder = 'Password';
    password2.placeholder = 'Confirm Password';
    first_name.placeholder = 'First Name';
    last_name.placeholder = 'Last Name';

</script>
{% endblock %}